### ISSUE TITLE
maru-0.7 is lack of desktop settings

### ISSUE THREAD

**Issue by sherylynn** [maruos/android_platform_packages_apps_Settings#4]
android_platform_packages_apps_Settings/src/com/android/settings/

is lack of desktop settting

**Comment by pdsouza** [comment]
Hi, yes, we haven't merged in desktop settings into `maru-0.7` yet because we are splitting out that code into a separate app. See https://github.com/maruos/maruos/issues/127 which @utzcoz is working on with some help from @pintaf.

**Comment by sherylynn** [comment]
Wow, thank you for  your introduction , MaruSettings will be a great app to integrate maruos to single app

**Comment by pintaf** [comment]
In the meantime, you can replace 
packages/apps/Settings
with
https://github.com/pintaf/android_packages_apps_Settings/tree/maru-0.7

**Comment by pintaf** [comment]
Hi.
In the meantime you can
delete `package/apps/Settings`
and replace it with 
https://github.com/pintaf/android_packages_apps_Settings      branch maru-0.7
